### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Tereseus** [Chrismmint/Scoop#3]
After reviewing your code, running your tests and running you repo I was only able to find one issue. Everything else you did was good, the only issue as stated in the other issue is that the voting number increases by 2 for comments. As soon as you fix this you will have completed this project. If you have any questions feel free to ask the advisors.

**Comment by Chrismmint** [comment]
Hi,

Issue is fixed now, I had two commands adding the username to upvotedby/downvotedby.
